language: node_js
node_js:
  - "8.9.1"
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - yarn test
  - yarn run build
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $githubToken
  keep-history: true
  on:
    branch: master
